### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by larenelg** [jawdinmorris/basic_web_scraper#1]
Well done!! What you have works, and it is easy to read and understand your code :)

A bit of a code review:
* don’t checkin `node_modules`. Add a `.gitignore`  file
* don’t need the export [line 115](https://github.com/jawdinmorris/basic_web_scraper/blob/2a5a145132f2841cc5a762d86cd0ca2ab3ce6877/app/main.js#L115), if you’re not importing it anywhere
* I learnt something! :) I’ve never heard of Cheerio before

Some tips:
* `npm run start` should be the `node main.js` command — add to `package.json`:
```
"scripts": {
    "start": "node main.js"
  }
```
* move everything out of ‘app’ and put it in the root folder (where the README is), so you can run `npm install` in the same directory as your README
* when adding dependencies, make sure you use `npm install —save <package-name>` so that it saves the version in the `package.json` and also generates a `package-lock.json`

Otherwise, LGTM 👍

**Comment by jawdinmorris** [comment]
Hi Larene! 
This is brilliant. I really appreciate you taking the time out to review it. 
I'll sit down and implement these changes soon. I'm quite rusty (and beginner) in node so really appreciate the tips!

**Comment by jawdinmorris** [comment]
All changes have now been implemented. Appreciate it!
